---
- name: User management
  ansible.builtin.import_tasks: user.yml
  tags: [users]

- name: SSH hardening
  ansible.builtin.import_tasks: ssh.yml
  tags: [ssh]

- name: Firewall
  ansible.builtin.import_tasks: firewall.yml
  tags: [firewall]

- name: Automatic updates
  ansible.builtin.import_tasks: updates.yml
  tags: [updates]

- name: Brute-force protection
  ansible.builtin.import_tasks: fail2ban.yml
  tags: [fail2ban]
